### ISSUE TITLE
The zip file of VM image is broken

### ISSUE THREAD

**Issue by husttroy** [Programming-Systems-Lab/dyclink#3]
I got the following error when unzipping the zip file of VM image on Ubuntu 14.04.

Archive:  dyclink_exec.zip
warning [dyclink_exec.zip]:  8589934592 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  8589934592
  (attempting to re-compensate)
   creating: dyclink_exec/
  inflating: dyclink_exec/.DS_Store  
   creating: __MACOSX/
   creating: __MACOSX/dyclink_exec/
  inflating: __MACOSX/dyclink_exec/._.DS_Store  
  inflating: dyclink_exec/dyclink_fse.tar.gz  
  inflating: __MACOSX/dyclink_exec/._dyclink_fse.tar.gz  
  inflating: dyclink_exec/dyclink_vm.zip  
  error:  invalid compressed data to inflate
file #9:  bad zipfile offset (local header sig):  801828549
  (attempting to re-compensate)
  inflating: __MACOSX/._dyclink_exec

I am able to extract the dyclink_vm.zip file but couldn't unzip it. 

Archive:  dyclink_vm.zip
  End-of-central-directory signature not found.  Either this file is not a zipfile, or it constitutes one disk of a   
  multi-part archive.  In the latter case the central directory and zipfile comment will be found on the last  
  disk(s) of this archive.
unzip:  cannot find zipfile directory in one of dyclink_vm.zip or dyclink_vm.zip.zip, and cannot find dyclink_vm.zip.ZIP, period.

**Comment by kiran2s** [comment]
I am getting the same issue. It seems like the .zip file is corrupted.

**Comment by mikefhsu** [comment]
Sorry for my late response, but could you send me the command that you used and which environment that you attempted to unzip the file?

One of our artifact evaluation committee member told me that the package cannot be unzipped on Windows machine, while the others told us that they can unzip the file successfully on Linux machines. I personally used a Mac to zip this package.

I will take a look when I am available. Thanks.

**Comment by tianyi-zhang** [comment]
@mikefhsu  I used the following command to unzip it in Ubuntu 14.04.
`unzip dyclink_exec.zip`

**Comment by jon-bell** [comment]
I had no problem unzip'ing using the Mac OS X archive utility, but did see the same issue with `unzip`. PKZip might do better here. I'm re-compressing as a .tgz and I'll post on Dropbox...

**Comment by jon-bell** [comment]
Please try this link:
https://www.dropbox.com/s/4fltzp7dlwmxf89/dyclink_exec.tgz?dl=1

**Comment by jon-bell** [comment]
Closing per Jens' email ("The archive works, thank you very much!")
